name = "van-hien"
pages_build_output_dir = "dist"
compatibility_date = "2024-09-23"

[[d1_databases]]
binding = "DB"
database_name = "vanhien-db"
database_id = "de087f62-62c6-4896-8646-f70aa9fcbc72"

# KV — dedicated to van-hien
# DEV: a06e46fc32b34eb487df25e57d3a4dd5  (placeholder — update after namespace create)
# PROD: create via: npx wrangler kv namespace create VANHIEN_KV
[[kv_namespaces]]
binding = "CACHE"
id = "1527de16154a4bf3a1746d541f91a082"
